version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://SG-ShowAI-10861-mysql-master.servers.mongodirector.com:3306/showai_db
      - SPRING_DATASOURCE_USERNAME=sgroot
      - SPRING_DATASOURCE_PASSWORD=3qy0-Bi4vcRZPjeX
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=showai_db
      - MYSQL_ROOT_PASSWORD=3qy0-Bi4vcRZPjeX
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
